import { type NextPage } from "next";
import Head from "next/head";
import Link from "next/link";

import { api } from "~/utils/api";
import {
  SignIn,
  useUser,
  SignOutButton,
  SignedOut,
  SignInButton,
  SignedIn,
  UserButton,
} from "@clerk/nextjs";
import { useRouter } from "next/router";

const Home: NextPage = () => {
  const hello = api.example.hello.useQuery({ text: "from tRPC" });
  const user = useUser();
  const router = useRouter();

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="">
        <UserButton />
        <h1 className="">T3 demo</h1>
        <SignedIn>
          <SignOutButton />
        </SignedIn>
        <SignedOut>
          <Link href={"/auth"}>Signin</Link>
        </SignedOut>
      </main>
    </>
  );
};

export default Home;
